//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int id { get; set; }
        public string deposite_slip { get; set; }
        public string pay_mode { get; set; }
        public string bank_name { get; set; }
        public string payorder_number { get; set; }
        public Nullable<int> total_amount { get; set; }
        public string remarks { get; set; }
        public string upload { get; set; }
    }
}
